# This script should delete all Google Apps
# Including Play Store, YouTube, Talk etc.
# It requires superuser!
APPS=(
AmbientSensePrebuilt
AndroidForWork
AndroidMigratePrebuilt
AndroidPlatformServices
BackupRestoreConfirmation
Books
BooksPhone
BooksStub
BrowserProviderProxy
CalculatorGoogle
CalculatorGooglePrebuilt
Calendar
CalendarGoogle
CalendarGooglePrebuilt
CalendarProvider
CarHomeGoogle
CellBroadcastReceiver
Chrome
ChromeBookmarksSyncAdapter
CloudPrint
CloudPrint2
com.android.chrome-1
ConfigUpdater
ConnMO
Currents
DeskClockGoogle
DMAgent
Drive
Duo
Earth
EditorsDocs
EditorsDocsStub
EditorsSheets
EditorsSheetsStub
EditorsSlides
EditorsSlidesStub
EuiccGoogle
ExchangeServices
FaceLock
Finsky
FitnessPrebuilt
FOTAKill
GalleryGoogle
GCS
GenieWidget
Gmail
Gmail2
GmsCore
GmsCoreSetupPrebuilt
GmsCore_update
GMS_Maps
GoogleBackupTransport
GoogleCalendar
GoogleCalendarSyncAdapter
GoogleCamera
GoogleCameraLegacy
GoogleCloudPrint
GoogleContacts
GoogleContactsSyncAdapter
GoogleDialer
GoogleEars
GoogleEarth
GoogleExtServices
GoogleExtShared
GoogleFeedback
GoogleHangouts
GoogleHindiIME
GoogleHome
GoogleJapaneseInput
GoogleKeep
GoogleLatinIme
GoogleLoginService
GoogleMusic
GoogleNow
GoogleNowVoiceSearch
GoogleOneTimeInitializer
GooglePartnerSetup
GooglePinyinIME
GooglePlay
GooglePlus
GooglePrintRecommendationService
GoogleQuickSearchBox
GoogleSearch
GoogleServicesFramework
GoogleTTS
GoogleVrCore
GoogleZhuyinIME
Hangouts
HangoutsDialer
HelpRtcPrebuilt
HotwordEnrollment
HotwordEnrollmentOKGoogleWCD9340
HotwordEnrollmentXGoogleWCD9340
iWnnIME
iWnnIME_Kbd_White
Keep
KoreanIME
LatinIME
LatinImeDictionaryPack
LatinImeGoogle
LatinIMEGooglePrebuilt
LatinImeTutorial
Magazines
Maps
MarketUpdater
MediaUploader
Music2
NetworkLocation
Newsstand
NewsstandStub
NewsWeather
NexusLauncherIcons
NexusLauncherPrebuilt
NexusWallpapersStubPrebuilt2017
OccamQuickOffice
OneTimeInitializer
PartnerBookmarksProvider
Phonesky
Photos
PlayAutoInstallConfig
PlayGames
PlayServices
PlayStore
PlusOne
PrebuiltBugle
PrebuiltBugleStub
PrebuiltDeskClockGoogle
PrebuiltEmailGoogle
PrebuiltExchange3Google
PrebuiltGmail
PrebuiltGmsCore
PrebuiltGmsCorePix
PrebuiltKeep
PrebuiltKeepStub
PrebuiltNewsWeather
PrintSpooler
QuickOffice
QuickSearchBox
SettingsGoogle
SetupWizard
StorageManagerGoogle
Street
SystemUIGoogle
Tag
TagGoogle
Talk
talkback
TranslatePrebuilt
Turbo
Tycho
Velvet
Velvet_update
Vending
Videos
VoicePlus
VoiceSearch
VoiceSearchStub
Wallet
WallpaperPickerGooglePrebuilt
WallpapersBReel2017
WebViewGoogle
WebViewStub
YouTube
70-gapps.sh
71-faceunlock.sh
71-gapps-faceunlock.sh
74-googlecamera.sh
74-googlegallery.sh
75-googlegallery.sh
78-chromebrowser.sh
/system/bin/wmdsi
/system/etc/ambient/matcher.leveldb
/system/etc/default-permissions/default-permissions.xml
/system/etc/default-permissions/opengapps-permissions.xml
/system/etc/firmware/dnd.descriptor
/system/etc/firmware/dnd.sound_model
/system/etc/firmware/music_detector.descriptor
/system/etc/firmware/music_detector.sound_model
/system/etc/g.prop
/system/etc/permissions/com.google.android.camera.experimental2015.xml
/system/etc/permissions/com.google.android.camera.experimental2016.xml
/system/etc/permissions/com.google.android.camera.experimental2017.xml
/system/etc/permissions/com.google.android.camera.experimental2018.xml
/system/etc/permissions/com.google.android.camera2.xml
/system/etc/permissions/com.google.android.dialer.support.xml
/system/etc/permissions/com.google.android.maps.xml
/system/etc/permissions/com.google.android.media.effects.xml
/system/etc/permissions/com.google.android.pano.v1.xml
/system/etc/permissions/com.google.vr.platform.xml
/system/etc/permissions/com.google.widevine.software.drm.xml
/system/etc/permissions/features.xml
/system/etc/preferred-apps/google.xml
/system/etc/sysconfig/dialer_experience.xml
/system/etc/sysconfig/framework-sysconfig.xml
/system/etc/sysconfig/google.xml
/system/etc/sysconfig/google_build.xml
/system/etc/sysconfig/google_vr_build.xml
/system/etc/sysconfig/pixel_2017.xml
/system/etc/sysconfig/pixel_2018.xml
/system/etc/sysconfig/whitelist_com.android.omadm.service.xml
/system/etc/updatecmds/google_generic_update.txt
/system/framework/com.google.android.camera.experimental2015.jar
/system/framework/com.google.android.camera.experimental2016.jar
/system/framework/com.google.android.camera2.jar
/system/framework/com.google.android.dialer.support.jar
/system/framework/com.google.android.maps.jar
/system/framework/com.google.android.media.effects.jar
/system/framework/com.google.android.pano.v1.jar
/system/framework/com.google.widevine.software.drm.jar
/system/lib/lib_dic_*
/system/lib/libAppDataSearch.so
/system/lib/libbitmap_parcel.so
/system/lib/libchrome*
/system/lib/libchromeview.so
/system/lib/libconscrypt_gmscore_jni.so
/system/lib/libcrashreporter.so
/system/lib/libdocscanner*
/system/lib/libdocsimageutils.so
/system/lib/libearthandroid.so
/system/lib/libearthmobile.so
/system/lib/libEnjemailuri.so
/system/lib/libennjcon.so
/system/lib/libennjubase*
/system/lib/libennjyomi.so
/system/lib/libfacelock_jni.so
/system/lib/libfacenet.so
/system/lib/libfacetracker.so
/system/lib/libfilterframework_jni.so
/system/lib/libfilterpack_facedetect.so
/system/lib/libflint_engine_jni_api.so
/system/lib/libfoxit.so
/system/lib/libframesequence.so
/system/lib/libfrsdk.so
/system/lib/libgames_rtmp_jni.so
/system/lib/libgcam.so
/system/lib/libgcam_swig_jni.so
/system/lib/libgcastv2*
/system/lib/libgcomm_jni.so
/system/lib/libgmm-jni.so
/system/lib/libgms-ocrclient.so
/system/lib/libgmscore.so
/system/lib/libgoggles_clientvision.so
/system/lib/libgoogle_*
/system/lib/libgtalk_jni.so
/system/lib/libgtalk_stabilize.so
/system/lib/libiwnn.so
/system/lib/libjgcastservice.so
/system/lib/libjni_eglfence.so
/system/lib/libjni_filtershow_filters.so
/system/lib/libjni_googlepinyinime_*
/system/lib/libjni_koreanime.so
/system/lib/libjni_latinime.so
/system/lib/libjni_latinimegoogle.so
/system/lib/libjni_t13n_shared_engine.so
/system/lib/libjni_tinyplanet.so
/system/lib/libjni_unbundled_latinimegoogle.so
/system/lib/liblightcycle.so
/system/lib/liblinearalloc.so
/system/lib/libm2ts_player.so
/system/lib/libmicro_hotword_jni.so
/system/lib/libmoviemaker-jni.so
/system/lib/libnativehelper_compat.so
/system/lib/libnativehelper_compat_libc++.so
/system/lib/libndk1.so
/system/lib/libnetjni.so
/system/lib/libnjaddress.so
/system/lib/libnjcon.so
/system/lib/libnjemoji.so
/system/lib/libnjexyomi.so
/system/lib/libnjfzk.so
/system/lib/libnjkaomoji.so
/system/lib/libnjname.so
/system/lib/libnjtan.so
/system/lib/libnjubase*
/system/lib/libnjubaseidx1.so
/system/lib/libnjubaseidx2.so
/system/lib/libocrclient.so
/system/lib/libpatts_engine_*
/system/lib/libphotoeditor_native.so
/system/lib/libpicowrapper.so
/system/lib/libplus_jni_v8.so
/system/lib/librectifier*
/system/lib/librefocus.so
/system/lib/librs.antblur.so
/system/lib/librs.antblur_*
/system/lib/librs.drama.so
/system/lib/librs.film_base.so
/system/lib/librs.fixedframe.so
/system/lib/librs.grey.so
/system/lib/librs.image_wrapper.so
/system/lib/librs.layered_filter_f32.so
/system/lib/librs.retrolux.so
/system/lib/librsjni.so
/system/lib/libRSSupport.so
/system/lib/libsense.so
/system/lib/libspeexwrapper.so
/system/lib/libspeexwrapper_ub*
/system/lib/libsslwrapper_jni.so
/system/lib/libstlport_shared.so
/system/lib/libvcdecoder_jni.so
/system/lib/libvideochat_jni.so
/system/lib/libvideochat_stabilize.so
/system/lib/libvoicesearch.so
/system/lib/libvorbisencoder.so
/system/lib/libwallpapers-breel-jni.so
/system/lib/libwebp_android.so
/system/lib/libwebrtc_audio_coding.so
/system/lib/libWhisper.so
/system/lib/libWVphoneAPI.so
/system/lib/modules/modules.dep.bb
/system/lib64/lib_dic_*
/system/lib64/libAppDataSearch.so
/system/lib64/libbitmap_parcel.so
/system/lib64/libchrome*
/system/lib64/libchromeview.so
/system/lib64/libconscrypt_gmscore_jni.so
/system/lib64/libcrashreporter.so
/system/lib64/libdocscanner*
/system/lib64/libdocsimageutils.so
/system/lib64/libearthandroid.so
/system/lib64/libearthmobile.so
/system/lib64/libEnjemailuri.so
/system/lib64/libennjcon.so
/system/lib64/libennjubase*
/system/lib64/libennjyomi.so
/system/lib64/libfacelock_jni.so
/system/lib64/libfacenet.so
/system/lib64/libfacetracker.so
/system/lib64/libfilterframework_jni.so
/system/lib64/libfilterpack_facedetect.so
/system/lib64/libflint_engine_jni_api.so
/system/lib64/libfoxit.so
/system/lib64/libframesequence.so
/system/lib64/libfrsdk.so
/system/lib64/libgames_rtmp_jni.so
/system/lib64/libgcam.so
/system/lib64/libgcam_swig_jni.so
/system/lib64/libgcastv2*
/system/lib64/libgcomm_jni.so
/system/lib64/libgmm-jni.so
/system/lib64/libgms-ocrclient.so
/system/lib64/libgmscore.so
/system/lib64/libgoggles_clientvision.so
/system/lib64/libgoogle_*
/system/lib64/libgtalk_jni.so
/system/lib64/libgtalk_stabilize.so
/system/lib64/libiwnn.so
/system/lib64/libjgcastservice.so
/system/lib64/libjni_eglfence.so
/system/lib64/libjni_filtershow_filters.so
/system/lib64/libjni_googlepinyinime_*
/system/lib64/libjni_koreanime.so
/system/lib64/libjni_latinime.so
/system/lib64/libjni_latinimegoogle.so
/system/lib64/libjni_t13n_shared_engine.so
/system/lib64/libjni_tinyplanet.so
/system/lib64/libjni_unbundled_latinimegoogle.so
/system/lib64/liblightcycle.so
/system/lib64/liblinearalloc.so
/system/lib64/libm2ts_player.so
/system/lib64/libmicro_hotword_jni.so
/system/lib64/libmoviemaker-jni.so
/system/lib64/libnativehelper_compat.so
/system/lib64/libnativehelper_compat_libc++.so
/system/lib64/libndk1.so
/system/lib64/libnetjni.so
/system/lib64/libnjaddress.so
/system/lib64/libnjcon.so
/system/lib64/libnjemoji.so
/system/lib64/libnjexyomi.so
/system/lib64/libnjfzk.so
/system/lib64/libnjkaomoji.so
/system/lib64/libnjname.so
/system/lib64/libnjtan.so
/system/lib64/libnjubase*
/system/lib64/libnjubaseidx1.so
/system/lib64/libnjubaseidx2.so
/system/lib64/libocrclient.so
/system/lib64/libpatts_engine_*
/system/lib64/libphotoeditor_native.so
/system/lib64/libpicowrapper.so
/system/lib64/libplus_jni_v8.so
/system/lib64/librectifier*
/system/lib64/librefocus.so
/system/lib64/librs.antblur.so
/system/lib64/librs.antblur_*
/system/lib64/librs.drama.so
/system/lib64/librs.film_base.so
/system/lib64/librs.fixedframe.so
/system/lib64/librs.grey.so
/system/lib64/librs.image_wrapper.so
/system/lib64/librs.layered_filter_f32.so
/system/lib64/librs.retrolux.so
/system/lib64/librsjni.so
/system/lib64/libRSSupport.so
/system/lib64/libsense.so
/system/lib64/libspeexwrapper.so
/system/lib64/libspeexwrapper_ub*
/system/lib64/libsslwrapper_jni.so
/system/lib64/libstlport_shared.so
/system/lib64/libvcdecoder_jni.so
/system/lib64/libvideochat_jni.so
/system/lib64/libvideochat_stabilize.so
/system/lib64/libvoicesearch.so
/system/lib64/libvorbisencoder.so
/system/lib64/libwallpapers-breel-jni.so
/system/lib64/libwebp_android.so
/system/lib64/libwebrtc_audio_coding.so
/system/lib64/libWhisper.so
/system/lib64/libWVphoneAPI.so
/system/lib64/modules/modules.dep.bb
/system/tts
/system/usr/srec
/system/vendor/lib/libfrsdk.so
/system/vendor/lib64/libfrsdk.so
/system/vendor/pittpatt

	
)

## DELETE APPS NOW ##

if [ "$USER_ID" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
echo "Remounting /system..."
mount -o remount,rw /system
echo "Deleteing..."
for i in ${APPS[@]}; do
	/system/priv-app/$i*
	/system/app/$i*
	/system/addon.d/$i*
	 
	 
done
echo "Cleaning Cache..."
 /data/dalvik-cache
 /cache/dalvik-cache
echo "Rebooting..."
reboot


 
